doctrine:
    dbal:
#        dbname: '%env(resolve:DATABASE_NAME)%'
        driver: '%env(resolve:DATABASE_DRIVER)%'
        path: '%env(resolve:DATABASE_PATH)%'
#        host: '%env(resolve:DATABASE_HOST)%'
#        password: '%env(resolve:DATABASE_PASSWORD)%'
#        porta: '%env(resolve:DATABASE_PORT)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/Mapping'
                prefix: 'App\Entity'
                alias: App
